---
- name: Create fabric directory
  file:
    path: "/var/www/fabric"
    state: directory

- name: Create novnc HTML
  template:
    dest: "/var/www/fabric/index.html"
    src: index.html.j2
    mode: 0644

- name: Download fabric
  get_url:
    url: "{{ fabric_release_url }}/{{ fabric_version }}/main.js"
    dest: "/var/www/fabric/main.js"
