---
- name: Configure and install nginx
  tags: [nginx]
  ansible.builtin.include_tasks:
      file: nginx.yml
      args:
          apply:
              become: true

- name: Configure and install fabric
  tags: [fabric]
  ansible.builtin.include_tasks:
      file: fabric.yml
      args:
          apply:
              become: true
