---
- name: Configure and install nginx
  tags: [nginx]
  include_tasks: nginx.yml
  args:
    apply:
      become: yes
      notify: restart nginx

- name: Configure and install fabric
  tags: [fabric]
  include_tasks: fabric.yml
  args:
    apply:
      become: yes
