---
- name: Install nginx package
  tags: [install]
  apt:
    name: nginx
    state: present

- name: Remove default config
  file:
    path: "{{ item }}"
    state: absent
  with_items: ["/etc/nginx/sites-enabled/default", "/etc/nginx/conf.d"]
  notify: restart nginx

- name: Add NGINX configuration file
  template:
    dest: /etc/nginx/sites-enabled/novnc.conf
    src: nginx_novnc.conf.j2
    mode: 0644
  notify: restart nginx

- name: Ensure the htpasswd utility is installed.
  apt:
    name: ["apache2-utils", "python3-passlib"]
    state: present
  when: htpasswd_credentials

- name: Ensure htpasswd credentials are configured.
  htpasswd:
    path: "/etc/nginx/passwdfile"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: "root"
    group: "www-data"
    mode: "0640"
  with_items: "{{ htpasswd_credentials }}"
  no_log: true
