---
- name: Install nginx package
  tags: [install]
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Remove default config
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items: ["/etc/nginx/sites-enabled/default", "/etc/nginx/conf.d"]
  notify: restart nginx

- name: Add NGINX configuration file
  ansible.builtin.template:
    dest: /etc/nginx/sites-enabled/novnc.conf
    src: nginx_novnc.conf.j2
    mode: 0644
  notify: restart nginx

- name: Ensure the htpasswd utility is installed
  ansible.builtin.apt:
    name: ["apache2-utils", "python3-passlib"]
    state: present
  when: novnc_htpasswd_credentials

- name: Ensure htpasswd credentials are configured
  community.general.htpasswd:
    path: "/etc/nginx/passwdfile"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: "root"
    group: "www-data"
    mode: "0640"
  with_items: "{{ novnc_htpasswd_credentials }}"
  no_log: true

- name: Per User htpasswd
  community.general.htpasswd:
    path: "/etc/nginx/passwd-{{ item.name }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    owner: "root"
    group: "www-data"
    mode: "0640"
  with_items: "{{ novnc_htpasswd_credentials }}"
  no_log: true
